### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Rapster** [CodyHouse/vertical-timeline#8]
Is it possible to indicate the license used? Github provides a nice way to indicate which license is being used https://help.github.com/articles/licensing-a-repository/

**Comment by claudia-romano** [comment]
Hi Rapster, you can find the link to our terms is in the readme file.
https://codyhouse.co/terms/

**Comment by Rapster** [comment]
I'd like to port this component on Primefaces Extensions (https://github.com/primefaces-extensions), but the terms are not cleared to me regarding what I want to do with it

> You cannot distribute a “pluginized” version of our resources (even for free).

Not sure if it matches a new component in a JSF library apache licensed

**Comment by Rapster** [comment]
@claudia-romano ?

**Comment by sebastiano-guerriero** [comment]
Hi Rapster,

I'm not 100% sure what the PrimeFace project is. In general, our terms do not allow to take one our resources, convert it into a component and release it to the public (while you're free to integrate our resources as a component into a personal/client project, where the goal is not redistribution). Therefore it depends on where your case falls. Cheers

**Comment by Rapster** [comment]
Well, I must say I'm kinda confused... Basically, the idea is to make your vertical timeline a JSF component. One of perk of the JSF is to "hide" the complexity of HTML/CSS/JS, so the component can be very easy to set up in a xhtml page. Primefaces Extensions is an Apache 2.0 licensed library, many of the components are based on jQuery components, we don't make any modifications of the original component (although we can request you improvements by making PR, if you like the request).

At the end, users reused as-is the component in their pages. I'm not sure what you mean by redistribution. Thanks for enlightening this please

**Comment by sebastiano-guerriero** [comment]
I see, well the current license does not allow this kind of use (even if the resource is used as is). The idea was to limit the use of our resources to personal/client projects. Redistribution, on the other side, includes 1) making a plugin of one of our resources and selling it or redistributing it for free, and 2) creating a component (e.g. a react component) and allowing users to download it (for sale or for free). Basically, any case where users can download our resource in a way other than our GitHub repos.

BUT we're in the process of reviewing our license, and we're probably going to use a MIT license where redistribution is allowed if credits are given, like in your case. We're going to complete the review process of the license in max 2 weeks.

**Comment by Rapster** [comment]
Alright, it's all clear now. Look forward to see a more open license then :wink:
