### ISSUE TITLE
style.css breaks page design

### ISSUE THREAD

**Issue by shnabz** [CodyHouse/vertical-timeline#9]
Is there any way to make the style.css only apply to the vertical timeline, and not override the css for the rest of the page?

**Comment by claudia-romano** [comment]
Hi there!
If you take a look at the style file, you'll see that there's a 'Primary style' part that we used for some basic style (like font family and colors) that you can remove (just make sure to keep the box-sizing declaration) and some additional style applied to the header tag that you can remove as well. All the remaining style is applied to the .cd-timeline element (and children) so it shouldn't affect the rest of your page.
